---
# title: ""
output: github_document
---

# Evaluating Biomarkers using Panel Current Status Data with Misclassication Errors

__NOTE__: WORK IN PROGRESS!

__GitHub Repository__: <https://github.com/celehs/misclassification/>

## Installation

Install development version from GitHub.

```{r, eval=FALSE}
# install.packages("remotes")
devtools::install_github("celehs/misclassification")
```

Load the package into R.

```{r}
library(misclassification)
```

## Simulated Example

```{r}
source("examples/mkdata.R")
```

```{r}
beta <- 1.2
lambda0 <- 0.01 * (1:5)
theta <- c(0.9, 0.88, 0.85, 0.8, 0.75)
phi <- rep(0.95, 5)
n <- 5000
data <- mkdata(
      beta = beta,
      lambda0 = lambda0,
      theta = theta,
      phi = phi,
      n = n,
      seed = 1)
data.table::data.table(data)
```

```{r}
with(data, addmargins(table(d0, t0)))
```

### Model Fitting

```{r}
# sensitivity unknown, specificity fixed
start <- c(beta, qlogis(lambda0), qlogis(theta)) # 1 + 5 + 5
fit <- optim(
   par = start,
   fn = function(par) {
      -loglik(
         beta = par[1],
         lambda0 = plogis(par[1 + 1:5]),
         theta = plogis(par[6 + 1:5]), # sensitivity
         phi = phi, # specificity
         t0 = data$t0,
         d0 = data$d0,
         X = data$z)
      },
      method = "BFGS")
# convergence (An integer code. 0 indicates successful completion)
fit$convergence
```

```{r}
data.frame(name = c("beta", 
                    paste0("lambda0_", 1:5), 
                    paste0("theta_", 1:5)),
           truth = c(start[1], plogis(start[-1])), 
           param = round(c(fit$par[1], plogis(fit$par[-1])), 3))
```

```{r}
# cumulative baseline hazards
data.frame(name = paste0("Lambda0_", 1:5),
           truth = cumsum(lambda0),
           param = round(cumsum(plogis(fit$par[1 + 1:5])), 3))
```

### Accuracy Measures

```{r}
# AUC at estimated parameters
est <- acc_est(
   Z = data$z, 
   beta = fit$par[1], 
   lambda0 = plogis(fit$par[1 + 1:5]))
est$AUC
```

```{r}
# AUC at true parameters
acc_est(
   Z = data$z, 
   beta = beta, 
   lambda0 = lambda0)$AUC
```

```{r ROC, fig.height=10}
par(mfrow = c(3, 2))
for (m in 1:5) {
   x <- c(0, est$FPR[, m])
   y <- c(0, est$TPR[, m])
   plot(x, y, las = 1, 
        type = "s", col = "blue",
        xaxs = "i", yaxs = "i", 
        xlab = "FPR", ylab = "TPR",
        main = paste0("t = ", m, " (AUC = ", 
                     sprintf("%.3f", est$AUC[m]), ")"))
      abline(a = 0, b = 1, lty = 2)   
}
```

```{r}
proc.time()
```
